export const config = {  
  OPENAI_API_KEY: process.env.NEXT_PUBLIC_OPENAI_API_KEY,
  ORGANIZATION_ID: process.env.NEXT_PUBLIC_ORGANIZATION,
  PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  SUPABASE_SERVICE_ROLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY
};