export const config = {  
  OPENAI_API_Key: process.env.NEXT_PUBLIC_OPENAI_API_KEY,
  PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  SUPABASE_SERVICE_ROLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY
};